from PyQt5 import QtCore, QtGui, QtWidgets
from RegisterBusinessLogic import Register_BL
import sys
import os

class Ui_RegisterWindow(object):
    def __init__(self):
        super(Ui_RegisterWindow, self)
        
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(216, 267)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        RegisterWindow.setPalette(palette)
        self.Label_FirstName = QtWidgets.QLabel(RegisterWindow)
        self.Label_FirstName.setGeometry(QtCore.QRect(10, 170, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_FirstName.setFont(font)
        self.Label_FirstName.setObjectName("Label_FirstName")
        self.Label_SignUp1 = QtWidgets.QLabel(RegisterWindow)
        self.Label_SignUp1.setGeometry(QtCore.QRect(80, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_SignUp1.setFont(font)
        self.Label_SignUp1.setObjectName("Label_SignUp1")
        self.Label_SignUp2 = QtWidgets.QLabel(RegisterWindow)
        self.Label_SignUp2.setGeometry(QtCore.QRect(50, 30, 131, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_SignUp2.setFont(font)
        self.Label_SignUp2.setObjectName("Label_SignUp2")
        self.Label_Username = QtWidgets.QLabel(RegisterWindow)
        self.Label_Username.setGeometry(QtCore.QRect(10, 110, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Username.setFont(font)
        self.Label_Username.setObjectName("Label_Username")
        self.pushButton_Cancel = QtWidgets.QPushButton(RegisterWindow)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(120, 230, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Cancel.setFont(font)
        self.pushButton_Cancel.setAutoFillBackground(False)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.lineEdit_Password = QtWidgets.QLineEdit(RegisterWindow)
        self.lineEdit_Password.setGeometry(QtCore.QRect(90, 140, 113, 20))
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.Label_LastName = QtWidgets.QLabel(RegisterWindow)
        self.Label_LastName.setGeometry(QtCore.QRect(10, 200, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_LastName.setFont(font)
        self.Label_LastName.setObjectName("Label_LastName")
        self.lineEdit_FirstName = QtWidgets.QLineEdit(RegisterWindow)
        self.lineEdit_FirstName.setGeometry(QtCore.QRect(90, 170, 113, 20))
        self.lineEdit_FirstName.setObjectName("lineEdit_FirstName")
        self.pushButton_Register = QtWidgets.QPushButton(RegisterWindow)
        self.pushButton_Register.setGeometry(QtCore.QRect(20, 230, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Register.setFont(font)
        self.pushButton_Register.setObjectName("pushButton_Register")
        self.lineEdit_LastName = QtWidgets.QLineEdit(RegisterWindow)
        self.lineEdit_LastName.setGeometry(QtCore.QRect(90, 200, 113, 20))
        self.lineEdit_LastName.setObjectName("lineEdit_LastName")
        self.Label_Password = QtWidgets.QLabel(RegisterWindow)
        self.Label_Password.setGeometry(QtCore.QRect(10, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Password.setFont(font)
        self.Label_Password.setObjectName("Label_Password")
        self.lineEdit_Username = QtWidgets.QLineEdit(RegisterWindow)
        self.lineEdit_Username.setGeometry(QtCore.QRect(90, 110, 113, 20))
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.Label_StatusSignUp = QtWidgets.QLabel(RegisterWindow)
        self.Label_StatusSignUp.setGeometry(QtCore.QRect(10, 60, 191, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_StatusSignUp.setFont(font)
        self.Label_StatusSignUp.setObjectName("Label_StatusSignUp")
        
        self.pushButton_Register.clicked.connect(self.RegisterUser)
        self.pushButton_Cancel.clicked.connect(self.GoToLoginWin)
        
        self.RegisterBL = Register_BL()
 
        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)
        RegisterWindow.setTabOrder(self.lineEdit_Username, self.lineEdit_Password)
        RegisterWindow.setTabOrder(self.lineEdit_Password, self.lineEdit_FirstName)
        RegisterWindow.setTabOrder(self.lineEdit_FirstName, self.lineEdit_LastName)
        RegisterWindow.setTabOrder(self.lineEdit_LastName, self.pushButton_Register)
        RegisterWindow.setTabOrder(self.pushButton_Register, self.pushButton_Cancel)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Register"))
        self.Label_FirstName.setText(_translate("RegisterWindow", "First Name:"))
        self.Label_SignUp1.setText(_translate("RegisterWindow", "Sign Up"))
        self.Label_SignUp2.setText(_translate("RegisterWindow", "Create An Account"))
        self.Label_Username.setText(_translate("RegisterWindow", "Username:"))
        self.pushButton_Cancel.setText(_translate("RegisterWindow", "Cancel"))
        self.Label_LastName.setText(_translate("RegisterWindow", "Last Name:"))
        self.pushButton_Register.setText(_translate("RegisterWindow", "Register"))
        self.Label_Password.setText(_translate("RegisterWindow", "Password:"))
        self.Label_StatusSignUp.setText(_translate("RegisterWindow", "Status"))
        self.Label_StatusSignUp.hide()
        
    def RegisterUser(self):
        self.Label_StatusSignUp.show()
        
        if self.RegisterBL.AreFieldsBlank(self.lineEdit_Username.text(), self.lineEdit_Password.text(), self.lineEdit_FirstName.text(), self.lineEdit_LastName.text()):
            self.Label_StatusSignUp.setStyleSheet("color: red;")
            self.Label_StatusSignUp.setText("One Of The Fields Are Empty!")
        
        elif self.RegisterBL.IsUsernameExistInData(self.lineEdit_Username.text()):
            self.Label_StatusSignUp.setStyleSheet("color: red;")
            self.Label_StatusSignUp.setText("The Username Entered \nAlready Exists!")
            
        else:
            self.RegisterBL.AddUserToData(self.lineEdit_Username.text(), self.lineEdit_Password.text(), self.lineEdit_FirstName.text(), self.lineEdit_LastName.text())
            self.Label_StatusSignUp.setStyleSheet("color: green;")
            self.Label_StatusSignUp.setText("Added New User!")
        
            self.lineEdit_Username.setText("")
            self.lineEdit_Password.setText("")
            self.lineEdit_FirstName.setText("")
            self.lineEdit_LastName.setText("")
                      
    def GoToLoginWin(self):
        RegisterWindow.hide()
        os.system("LoginBusinessLogic.py")



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    RegisterWindow = QtWidgets.QDialog()
    ui = Ui_RegisterWindow()
    ui.setupUi(RegisterWindow)
    RegisterWindow.show()
    sys.exit(app.exec_())

